import type { Metadata } from "next";import { redirect } from "next/navigation";import { AppShell } from "@/components/app-shell";import { createClient } from "@/lib/supabase/server";
export const metadata:Metadata={title:"Season"};export const dynamic="force-dynamic";
export default async function Page(){
 const supabase=await createClient();if(!supabase)redirect("/auth/sign-in");const {data:{user}}=await supabase.auth.getUser();if(!user)redirect("/auth/sign-in");
 const {data:weeks}=await supabase.from("competition_weeks").select("*").order("start_date");const completed=(weeks??[]).filter(w=>w.status==="settled").length;const active=(weeks??[]).filter(w=>w.is_active_betting_week).length;
 return <AppShell><main className="content"><div className="page-head"><div><p className="eyebrow">The full script</p><h1>Season</h1><p className="subtle">Competition weeks follow the calendar—not official matchweeks.</p></div></div>
 <div className="card" style={{marginBottom:18}}><div className="stat-row" style={{marginTop:0}}><div><span className="stat-label" style={{color:"var(--muted)"}}>Active weeks</span><span className="stat-value">{active}</span></div><div><span className="stat-label" style={{color:"var(--muted)"}}>Completed</span><span className="stat-value">{completed}</span></div><div><span className="stat-label" style={{color:"var(--muted)"}}>Current</span><span className="stat-value">{weeks?.find(w=>w.status==="open")?.number??"—"}</span></div></div></div>
 <div className="timeline">{(weeks??[]).map(w=>{const state=w.status==="settled"?"done":w.status==="open"?"current":w.status==="break"?"break":"";return <div className={`week ${state}`} key={w.id}><div className="week-icon">{state==="done"?"✓":w.status==="break"?"🌍":w.number}</div><div className="week-body"><div className="week-title"><span>{w.label}</span><span className="subtle" style={{fontSize:12}}>{new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric"}).format(new Date(`${w.start_date}T12:00:00`))}</span></div><div className="week-meta">{w.notes??(w.is_active_betting_week?"Competition week":"No picks")}</div></div></div>})}</div>
 <div className="notice" style={{marginTop:18}}><b>Second Half begins after the First Half script.</b><br/>Bankroll carries forward, while performance restarts from zero.</div></main></AppShell>
}
